export interface MockListing {
  id: string;
  sellerId: string;
  title: string;
  description: string;
  price: number;
  category: string;
  imageUrl: string;
  campus: string;
  residence: string;
  status: 'active' | 'sold' | 'suspended' | 'expired';
  reportCount: number;
  createdAt: string;
  expiresAt: string;
  contactCount: number;
}

const now = new Date();
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
const fourDaysAhead = new Date(now.getTime() + 4 * 24 * 60 * 60 * 1000);
const yesterday = new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000);

const defaultCreatedAt = threeDaysAgo.toISOString();
const defaultExpiresAt = fourDaysAhead.toISOString();
const expiredExpiresAt = yesterday.toISOString();

export const MOCK_LISTINGS: MockListing[] = [
  {
    id: 'l1',
    sellerId: 'u1',
    title: 'Engineering Mathematics 3 Textbook',
    description: 'Kreyszig Advanced Engineering Mathematics 10th edition. No writing inside, spine intact. Selling because I passed the module.',
    price: 350,
    category: 'textbooks',
    imageUrl: 'https://picsum.photos/seed/l1/400/300',
    campus: 'Wits University',
    residence: 'Dalrymple House',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 4,
  },
  {
    id: 'l2',
    sellerId: 'u2',
    title: 'Homemade Chicken Wings (12 pieces)',
    description: 'Freshly made peri-peri chicken wings. Available tonight from 8pm. Pickup at Jubilee Hall kitchen entrance. Cash or in-app payment.',
    price: 45,
    category: 'food',
    imageUrl: 'https://picsum.photos/seed/l2/400/300',
    campus: 'Wits University',
    residence: 'Jubilee Hall',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 7,
  },
  {
    id: 'l3',
    sellerId: 'u4',
    title: 'Laundry Service — Wash & Fold',
    description: 'Drop off your laundry in the morning, get it back same evening washed and folded. R50 per load. Dalrymple House room 204.',
    price: 50,
    category: 'laundry',
    imageUrl: 'https://picsum.photos/seed/l3/400/300',
    campus: 'Wits University',
    residence: 'Dalrymple House',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 3,
  },
  {
    id: 'l4',
    sellerId: 'u1',
    title: 'MATH1004 Tutoring Sessions',
    description: 'One-on-one tutoring for MATH1004. I scored 85% last semester. Sessions are 1 hour, held in the study room. Bring your notes.',
    price: 80,
    category: 'tutoring',
    imageUrl: 'https://picsum.photos/seed/l4/400/300',
    campus: 'Wits University',
    residence: 'Dalrymple House',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 5,
  },
  {
    id: 'l5',
    sellerId: 'u3',
    title: 'Samsung Galaxy A14 — Good Condition',
    description: 'Used for 8 months. Screen has a small scratch on the corner but barely visible. Comes with charger and case. No box.',
    price: 1200,
    category: 'electronics',
    imageUrl: 'https://picsum.photos/seed/l5/400/300',
    campus: 'Wits University',
    residence: 'International House',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 2,
  },
  {
    id: 'l6',
    sellerId: 'u6',
    title: 'Vintage Denim Jacket',
    description: 'Levi-style denim jacket, size M. Slightly worn in, looks great. Perfect for Joburg winters. Pickup at Dalrymple House.',
    price: 180,
    category: 'clothing',
    imageUrl: 'https://picsum.photos/seed/l6/400/300',
    campus: 'Wits University',
    residence: 'Dalrymple House',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 1,
  },
  {
    id: 'l7',
    sellerId: 'u2',
    title: 'Physics 2 Lab Manual — Sold!',
    description: 'Official lab manual for PHYS2002. All pages intact, no writing. Selling because the course is done.',
    price: 120,
    category: 'textbooks',
    imageUrl: 'https://picsum.photos/seed/l7/400/300',
    campus: 'Wits University',
    residence: 'Jubilee Hall',
    status: 'sold',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 3,
  },
  {
    id: 'l8',
    sellerId: 'u4',
    title: 'Ride to Sandton City — Saturday',
    description: 'Driving to Sandton City this Saturday morning at 9am. Leaving from Knockando Hall parking. 3 seats available. Return trip at 3pm.',
    price: 30,
    category: 'transport',
    imageUrl: 'https://picsum.photos/seed/l8/400/300',
    campus: 'Wits University',
    residence: 'Knockando Hall',
    status: 'sold',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 6,
  },
  {
    id: 'l9',
    sellerId: 'u3',
    title: 'USB-C Hub 7-in-1',
    description: 'Never used, still in box. Has HDMI, 2x USB 3.0, SD card reader, ethernet, USB-C PD. Bought wrong model for my laptop.',
    price: 250,
    category: 'electronics',
    imageUrl: 'https://picsum.photos/seed/l9/400/300',
    campus: 'Wits University',
    residence: 'International House',
    status: 'suspended',
    reportCount: 2,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 0,
  },
  {
    id: 'l10',
    sellerId: 'u5',
    title: 'Late Night Kota Special',
    description: 'Custom kota with chips, egg, cheese, and polony. Available from 9pm to midnight. Knockando Hall common room. Best in res!',
    price: 35,
    category: 'food',
    imageUrl: 'https://picsum.photos/seed/l10/400/300',
    campus: 'Wits University',
    residence: 'Knockando Hall',
    status: 'expired',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: expiredExpiresAt,
    contactCount: 12,
  },
  {
    id: 'l11',
    sellerId: 'u4',
    title: 'Statistics 2 Notes & Past Papers',
    description: 'Complete set of STAT2001 notes from lectures, plus 5 years of past papers with memos. Very helpful for exam prep. Digital copy available.',
    price: 60,
    category: 'textbooks',
    imageUrl: 'https://picsum.photos/seed/l11/400/300',
    campus: 'Wits University',
    residence: 'Dalrymple House',
    status: 'active',
    reportCount: 1,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 8,
  },
  {
    id: 'l12',
    sellerId: 'u5',
    title: 'Ironing Service — R15 per item',
    description: 'Drop off shirts, trousers, or dresses and get them ironed within 2 hours. Alan Paton Hall room 112. Best turnaround in res.',
    price: 15,
    category: 'laundry',
    imageUrl: 'https://picsum.photos/seed/l12/400/300',
    campus: 'Wits University',
    residence: 'Alan Paton Hall',
    status: 'active',
    reportCount: 0,
    createdAt: defaultCreatedAt,
    expiresAt: defaultExpiresAt,
    contactCount: 9,
  },
];
